
#+TITLE: Práctica completa de Estadística
#+DATE: 2022



* TODO Terminar Ejercicio 1.6

* TODO Terminar Ejercicio 2.2.c

* TODO Terminar ejercicio 2.4.b

* TODO Terminar ejercicio 2.5.d

#+begin_export latex
\clearpage
#+end_export

* Probabilidad

*1.* La probabilidad de resolver correctamente un problema con alguna de dos versiones de Octave es 0.45. La de resolver el problema con la primera de estas dos versiones es 0.40 y la de resolverlo con la segunda es 0.30. ¿Es independiente la resolución del problema con estas dos versiones? Justifique.


_Resolución_:
Dado X: la probabilidad de resolver el problema con la 1ra versión y Y: la probabilidad de resolverlo con la 2da versión, las probabilidades del enunciado son:
\begin{align*}
P(X) &= 0,40\\
P(Y) &= 0,30\\
P(X \cup Y ) &= 0,45.
\end{align*}

Para obtener la probabilidad conjunta usamos la fórmula de la probabilidad total.
\begin{align*}
P(X \cup Y ) &= P(X) + P(Y) - P(X \cap Y)\\
P(X \cap Y ) &= P(X) + P(Y) - P(X \cup\\
             &= 0,40 + 0,30 - 0,45\\
	     &= 0,25 \rightarrow 25\%
\end{align*}

Para saber si los eventos X y Y son independientes, su producto debería ser igual a su probabilidad conjunta:
$$
P(X) \cdot P(Y) = 0,40 \cdot 0,30 = 0,12 \neq 0,25 = P(X \cap Y)
$$
y por tanto *no son eventos independientes*.


------------------------------

*2.* Un correo en un Webmail Horde es revisado por dos algoritmos de antispam. Una política de seguridad decide que se muestren aquellos que cuenten con el visto bueno de por lo menos uno de los chequeos. Con este criterio pasan el 80 %. Se sabe que el el 60 % pasó el primer algoritmo y el segundo el 50 %. ¿Cuál hubiese sido el porcentaje de correos mostrados, si se hubiese exigido superar ambas revisiones?

_Resolución_:
Sea A el número de mails que pasan el primer algoritmo  y B los que pasan el segundo. La probabilidad de que un mail pase ambos chequeos simultaneamente $P(A \cap B)$ es
\begin{align*}
P(A) = 0,60 \quad \quad P(B) &= 0,50 \quad \quad P(A \cup B) = 0,80\\\\
P(A \cup B ) &= P(A) + P(B) - P(A \cap B)\\
P(A \cap B ) &= P(A) + P(B) - P(A \cup B)\\
             &= 0,60 + 0,50 - 0,80\\
	     &n= \mathbf{0,30} \rightarrow \mathbf{30\%}
\end{align*}


------------------------------

*3.* En una facultad hay 425 ingresantes de Ingeniería en Informática. En el primer cuatrimestre hay tres asignaturas por cursar: Matemática (A), Química (B) y Física (C). Del SIU Guaraní se obtuvo la siguiente información de cursado:

|-------------------+---------------|
| Asignatura        | N° de alumnos |
|-------------------+---------------|
| A                 |           120 |
| B                 |            70 |
| C                 |            60 |
| $A \cap B$        |            45 |
| $A \cap C$        |            45 |
| $B \cap C$        |            20 |
| $A \cap B \cap C$ |             5 |
|-------------------+---------------|

Suponga que un alumno es elegido al azar. Calcular las probabilidades de que concurra a:
a) Las 3 asignaturas.\\
b) Por lo menos una de las 3.\\
c) Sólo a Física.\\
d) Sólo a una asignatura.\\
e) Matemática pero no a Química.\\
f) Física o Matemática pero no a Química.\\


_Resolución_:

|-------------------+---------------+--------------|
| Asignatura        | N° de alumnos | Probabilidad |
|-------------------+---------------+--------------|
| A                 |           120 | 0,29         |
| B                 |            70 | 0,16         |
| C                 |            60 | 0,14         |
| $A \cap B$        |            45 | 0,11         |
| $A \cap C$        |            10 | 0,02         |
| $B \cap C$        |            20 | 0,05         |
| $A \cap B \cap C$ |             5 | 0,01         |
|-------------------+---------------+--------------|

a) La probabilidad de que concurran a las 3 materias simultáneamente es $P(A \cap B \cap C) = 0,01 \rightarrow 1%$.

b) La probabilidad de que asista a al menos una de las 3 es

\begin{align*}
P(A \cup B \cup C) &= P(A) + P(B) + P(C) - P(A \cap B) - P(A \cap C) - P(B \cap C) - 2P(A \cap B \cap C)\\
&= 0,29 + 0,16 + 0,14 - 0,11 - 0,02 - 0,05 - 2 \cdot 0,01\\
&= 0,39\\
\end{align*}

c)
\begin{align*}
P(C_0) &= P(C) - P(C \cap A) - P(C \cap B)\\
 &= 0,14 - 0,02 - 0,05 = 0,07 \rightarrow 7\%
\end{align*}

------------------------------

*4)*
Dos vendedores de una empresa con distinta antigüedad suelen llegar tarde a su trabajo; la probabili-
dad de que el vendedor con mayor antigüedad llegue tarde cierto día es 0.20; de que el vendedor de
menor antigüedad llegue tarde es 0.15 y de que ambos lleguen tarde es 0.09. Determine la probabili-
dad de que:\\
a) alguno llegue tarde cierto día.\\
b) sólo uno llegue tarde.\\
c) llegue tarde el de menor antigüedad sabiendo que lo hizo el de mayor antigüedad\\

_Resolución_:
Sea A el evento de que el vendedor con mayor antigüedad llegue tarde cierto día y B lo mismo para el vendedor de menor antigüedad, se tiene

$$
P(A) = 0,20 \quad \quad P(B) = 0,15 \quad \quad P(A \cap B) = 0,09
$$

a)
\begin{align*}
P(A \cup B) &= P(A) + P(B) - P(A \cap B)\\
&= 0,20 + 0,15 - 0,09\\
&= 0,26 \rightarrow 26\%
\end{align*}


b) La probabilidad de que sólo A ocurra lo llamamos A_0 y análogamente con B_0.

\begin{align*}
P(A_0) &= P(A) - P(A \cap B)\\
&= 0,20 - 0,09 = 0,11\\\\
P(B_0) &= P(B) - P(A \cap B)\\
&= 0,15 - 0,09 = 0,06
\end{align*}

Por lo tanto la probabilidad de que sólo uno llegue tarde es

$$
P(A_0 \cup B_0) = 0,11 + 0,06 = 0,17 \rightarrow 17\%
$$

\begin{align*}
P(B / A) &= \frac{P(A \cap B)}{P(A)}\\
&= \frac{0,09}{0,20} = 0,45 \rightarrow 45\%
\end{align*}

------------------------------

*5.* Una encuesta a ejecutivos se enfocó a su lealtad a la empresa. Una de las preguntas planteadas fue: Si otra compañía le hiciera una oferta igual o ligeramente mejor que la de su puesto actual, ¿permanecería con la empresa o tomaría el otro empleo? Las respuestas de los 200 ejecutivos de la encuesta se clasificaron en forma cruzada con su tiempo de servicio en la compañía y se muestran en la siguiente tabla.


|         | Tiempo de Servicio(años) | <1 | 1 a 5 | 6 a 10 | >10 |
|---------+--------------------------+----+-------+--------+-----|
| Lealtad | Permanecería             | 10 |    30 |      5 |  75 |
|         | No permanecería          | 25 |    15 |     10 |  30 |

Si se selecciona al azar un ejecutivo, calcule las siguientes probabilidades de los siguientes eventos:\\
a) el ejecutivo seleccionado es leal a la empresa.\\
b) el ejecutivo seleccionado tiene entre 1 y 5 años de servicio.\\
c) el ejecutivo seleccionado no es leal a la empresa y tiene entre 6 y 10 años de servicio.\\
d) Calcule la probabilidad de que el ejecutivo seleccionado tenga más de 10 años de servicio sabiendo que es leal a la empresa.\\


_Resolución_:

a) Sea A el evento de que el ejecutivo sea leal
$$
P(A) = \frac{10+30+5+75}{200} = 0,6 \rightarrow 60\%
$$

b) Sea B el evento de que el ejecutivo tenga entre 1 y 5 años de servicio
$$
P(B) = \frac{30+15}{200} = 0,23 \rightarrow 23\%
$$

c) Sea C el evento de que el ejecutivo no es leal a la empresa y D que tiene entre 6 a 10 años
$$P(C \cap D) = \frac{10}{200} = 0,05 \rightarrow 5\%$$

d) Sea E el evento de que el ejecutivo tenga más de 10 años en la empresa

$$P(E / A) = \frac{P(E \cap A)}{P(A)} = \frac{75/200}{0,6} = 0,62 \rightarrow 63\%$$

------------------------------

*6.* De los aspirantes a ingresar la tecnicatura en Software Libre el 40 % son varones, de los cuales sólo el 20 % ya es alumno de la UNL, mientras que entre las mujeres, el 30 % ya son alumnas. Se elige un aspirante al azar.
a) ¿Cuál es la probabilidad de que ya sea alumno?\\
b) Si el estudiante elegido ya es alumno, ¿cuál es la probabilidad de que sea varón?\\
c) ¿Cuál es la probabilidad de que sea mujer o que no sea alumno?\\

_Resolución_:

a) La probabilidad de que ya sea alumno puede obtenerse realizando un árbol de probabilidades resultando la probabilidad:
\begin{align*}
P(A) = P(A \cap V ) + P(A \cap M) &= P(V) \cdot P(A / V) + P(M) \cdot P(A / M)\\
&= 0,40 \cdot 0,20 + 0,60 \cdot 0,30 = 0,26 \rightarrow 26\%
\end{align*}

b)
\begin{align*} 
P( V / A ) &= \frac{P(V \cap A)}{P(A)}\\
&= \frac{P(V) \cdot P(A/V)} {P(A)} \\
&= \frac{0,40 \cdot 0,20} {0,26} \\
&= 0,31 \rightarrow 31\%
\end{align*}


c)

\begin{align*}
P(M \cup \bar{A}) &= P(M) + P(\bar{A}) \\
&= P(M) + P(V \cap \bar{A} ) + P(M \cap \bar{A} ) \\
&= 0,60 + 0,32 + 0,42 \\
&= 0,86 \rightarrow 86\%
\end{align*}


------------------------------

*7.* Los habitantes en situación de empleo de una determinada ciudad se ha dividido en función de sus ingresos anuales en tres grupos: el 20% tiene ingresos bajos, el 70% ingresos medios y el resto ingresos altos. Se ha determinado que la proporción de la población con estos ingresos que posee título universitario es 0.1, 0.9 y 0.3 respectivamente.\\
a) Determine, al elegir al azar un habitante, la probabilidad de que posea título universitario.\\
b) Si la persona seleccionada tiene título universitario, ¿a qué grupo pertenecería más probablemente?\\

_Resolución_:

Sean B ingresos bajos, M ingresos medios, A ingresos altos, T estudios universitarios. 

a)
\begin{align*}
P(T) &= P(T \cap B) + P(T \cap M) + P(T \cap A)\\
&= P(B) \cdot P(T / B) + P(M) \cdot P(T / M) + P(A) \cdot P(T / A)\\
&= 0,20 \cdot 0,1 + 0,70 \cdot 0,90 + 0,10 \cdot 0,30\\
&= 0,68 \rightarrow 68\%
\end{align*}

b)
\begin{align*}
P(B/T) &= \frac{P(B \cap T)}{P(T)} = \frac{0,03}{0,68} = 0,04 \rightarrow 4\% \\
P(M/T) &= \frac{P(M \cap T)}{P(T)} = \frac{0,63}{0,68} = 0,93 \rightarrow 93\% \\
P(A/T) &= \frac{P(A \cap T)}{P(T)} = \frac{0,02}{0,68} = 0,03 \rightarrow 3\%
\end{align*}

Por lo tanto, es más probable que pertenezca al grupo de ingresos medios.

------------------------------

*8.* En una fábrica de discos de estado sólido, el 20 % de los mismos se montan en la primera planta, el 30 % en la segunda y el 50 % restante en la tercera. Se sabe además que la cadena de montaje falla, dando lugar a una disco defectuoso, con probabilidades 0.1, 0.2 y 0.15 en cada una de las tres plantas respectivamente. Se selecciona al azar un disco montado en esa fábrica.\\
a) Determine la probabilidad de que sea defectuoso.\\
b) ¿Cuál es la probabilidad de que se haya montado en la primera planta sabiendo que es defectuoso?\\
c) Si el disco seleccionada resultó no defectuoso, ¿cuál es la probabilidad de que haya sido montado en la tercera planta.\\


_Resolución_:
Sea A el evento de que los discos se monten en la primera planta, B en la segunda y C en la tercera; y F el suceso de que el disco esté defectuoso. El enunciado nos da las siguientes probabilidades

\begin{align*}
&P(A) = 0,20      && P(B) = 0,30      &&& P(C) = 0,50\\
&P(F / A) = 0,10  && P(F / B) = 0,20  &&& P(F / C) = 0,15
\end{align*}

a)
\begin{align*}
P(F) &= P(F \cap A) + P(F \cap B) + P(F \cap C)\\
     &= P(A) \cdot P(F/A) + P(B) \cdot P(F/B) + P(C) \cdot P(F/C)\\
     &= 0,20 \cdot 0,10 + 0,30 \cdot 0,20 + 0,50 \cdot 0,15\\
     &= 0,16 \rightarrow 16\%
\end{align*}

b)
\begin{align*}
P(A/F) &= \frac{ P(A \cap F)} {P(F)} = \frac{0,02}{0,16}\\
       &= 0,13 \rightarrow 13\% 
\end{align*}

c)
$$
P(\bar{F})=1-P(F) = 1 - 0,16 = 0,84 \rightarrow 84\%
$$

\begin{align*}
P(C / \bar{F}) &= \frac{ P(C \cap \bar{F})} {P(\bar{F})}\\
               &= \frac{ P(C) \cdot P(\bar{F}/C)} {P(\bar{F})}\\
               &= \frac{0,50 \cdot 0,85} {0,84}\\
               &= 0,51 \rightarrow 51\%
\end{align*}


#+begin_export latex
\clearpage
#+end_export


* Variables aleatorias
*Ejercicio 1)* La distribución de probabilidad de X: "número de errores en un canal de transmisión" se presenta en la siguiente tabla:

|------+------+------+------+------+------|
| X    |    0 |    1 |    2 |    3 |    4 |
|------+------+------+------+------+------|
| f(x) | 0.41 | 0.37 | 0.16 | 0.05 | 0.01 |
|------+------+------+------+------+------|

Determinar la función acumulativa de X y utilizar la para determinar la probabilidad de encontrar más de 3 errores en el canal.

_Resolución_
|------+---+------+------+------+------+----|
| X    | 0 |    1 |    2 |    3 |    4 | >4 |
|------+---+------+------+------+------+----|
| F(x) | 0 | 0.41 | 0.78 | 0.94 | 0.99 |  1 |
|------+---+------+------+------+------+----|

La probabilidad de encontrar más de 3 errores es

$$
P(X>3) = 1 - P(X \leq 3) = 1 - 0.99 = 0.01 \Rightarrow 1\%.
$$

------------------------------

*Ejercicio 2.* Se está realizando un estudio en un sistema y se analiza una variable aleatoria X con función dada por:
\begin{align*}
F(x) = 
\left\{
      \begin{array}{ll}
            1-e^{-x} & \mbox{si } x > 0 \\
	    0        & \mbox{si } x \leq 0
      \end{array}
\right.
\end{align*}

a) Obtener P(X>2).\\

b) Considerar una nueva variable aleatoria Y que también es necesaria para el estudio de manera que la función de densidad conjunta de las variables es:

\begin{align*}
f(x,y) =
\left\{
      \begin{array}{ll}
            ye^{-(x+y)} & \mbox{si } x > 0 \land y > 0 \\
            0           & \mbox{en otro caso}
       \end{array}
\right.
\end{align*}

Indicar de forma razonada si se puede considerar que ambas variables son independientes ya que de esta conclusión depende parte del estudio.\\

c) En cualquier caso, calcular P(Y < 1 | X > 2).\\

_Resolución_:\\
*a)* La forma más rápida de hallar P(X>2) es mediante la función acumulativa que nos da el problema F(x), la cual por definición es la probabilidad de que la variable X sea menor o igual a cierto valor. Entonces
\begin{align*}
P(X > 2 ) & = 1 - P(X \leq 2 ) \quad \quad \mbox{Uso del complemento}\\
          & = 1 - F(2)\\
          & = 1 - (1 - e^{-2})\\
          & = 1 - 0,86 = 0,14 \Rightarrow \mathbf{14\%}
\end{align*}


La otra forma para hallar P(X>2) es hallando f(x) e integrando en el intervalo que nos interese saber su probabilidad. Para hallar f(x) mediante F(x), derivamos F(x) respecto de x.

\begin{align*}
\frac{d}{dx} F(x) &= \frac{d}{dx}(1-e^{-x})\\
                  &= \frac{d}{dx} 1 - \frac{d}{dx} e^{-x}\\
             \mathbf{f(x)} &= \mathbf{e^{-x}}
\end{align*}

Y ahora integramos respecto a x en el intervalo [2,+\infty)

\begin{align*}
P(X>2) = \int_2^{+ \infty} f(x)dx &= \int_2^{+ \infty} e^{-x} dx\\
       &= -e^{-x} \Big]_2^{+ \infty}\\
       &= e^{-2} - e^{-\infty} = 0,13 \Rightarrow \mathbf{13\%}
\end{align*}

*b)* Para saber si ambas variables son independientes se debe comprobar
$$
f(x,y) = f(x)\cdot f(y)
$$
por lo que vamos a obtener las funciones marginales para cada variable y comprobar si esta igualdad se cumple.

\begin{align*}
f(x) &= \int_{-\infty}^{ +\infty} f(x,y) dy \\
     &= \int_{0}^{ +\infty} y \cdot e^{-(x+y)} dy \\
     &= \int_{0}^{ +\infty} y \cdot e^{-x} \cdot e^{-y} dy \\
     &= e^{-x} \cdot \int_{0}^{ +\infty} y \cdot e^{-y} dy \\
     &= e^{-x} \cdot (-e^{-y} \cdot y - e^{-y})_0^{ + \infty} \\
f(x) &= e^{-x}\\\\
f(y) &= \int_{-\infty}^{+ \infty} f(x,y) dx\\
     &= \int_0^{ +\infty} y \cdot e^{-(x+y)} dx \\
     &= y \cdot e^{-y} \int_0^{ +\infty} e^{-x} dx \\
f(y) &= y \cdot e^{-y}
\end{align*}

Al realizar el producto

$$
f(x) \cdot f(y) = e^{-x} \cdot y \cdot e^{-y} = y \cdot e^{-(x+y)} = f(x,y)
$$
y por tanto son independientes.

*c)*

\begin{align*}
P(Y < 1 / X > 2) &= \frac{ P(Y < 1 \cap X > 2)} { P(X>2)} \\
\end{align*}


------------------------------

*Ejercicio 3.* Se conoce que la duración (en días) de un disco rígido es una variable aleatoria que se distribuye según la siguiente función:

\begin{align*}
f(x) =
\left\{
       \begin{array}{ll}
              1000/x^2 & \mbox{si } x > 1000 \\
              0 & \mbox{en otro caso}
       \end{array}
\right.
\end{align*}

Cuál es la probabilidad de que en un disco rígido dure menos de 2000 días, si se conoce que el disco funciona aún después de 1500 días de uso de la máquina?\\\\


_Resolución_: Esto es una probabilidad condicional que se calcula de la siguiente forma
\begin{align*}
    P(X < 2000 / X > 1500) &= \frac{ P( X < 2000 \cap X > 1500)} {P(X >1500)} \\
                           &= \frac{ \int_{1500}^{2000} 1000/x^2 dx } { \int_{1500}^{\infty} 1000/x^2 dx} \\
                           &= \frac{ -1000 [1/x]_{1500}^{2000} } { -1000 [1/x]_{1500}^{\infty} } \\
                           &= \frac{ 1/2000 - 1/1500 } { 1/\infty - 1/1500 } \\
                           &= 0,25 \rightarrow 25\%
\end{align*}


------------------------------

*Ejercicio 4.* Una variable aleatoria está distribuida según la ley que se muestra en la figura:



a) Encontrar una expresión para la función de densidad y verificar que sea válida.

b) Obtener la función de distribución correspondiente.\\

_Resolución_:
a)
\begin{align*}
f(x) =
\left\{
      \begin{array}{ll}
          \frac{x}{a^2} + \frac{1}{a} & \quad -a \leq x < 0 \\
          \frac{-x}{a^2} + \frac{1}{a} & \quad 0 \leq x \leq a\\
          0 & \mbox{En otro caso}
      \end{array}
\right.
\end{align*}

La probabilidad es el área bajo la función que puede calcularsse como dos mitades de un triangulo de lados $a$ y $1/a$

$$
Area = 2 \cdot \frac{a \cdot 1/a}{2} = \frac{2}{2}= 1
$$
por lo tanto es una función de probabilidad.\\

b) La función de distribución se obtiene integrando indefinidamente respecto a x ambas partes de la función
\begin{align*}
-a \leq x < 0 : F(x) & = \int \frac{x}{a^2} + \frac{1}{a} dx \\
     &= \frac{1}{a^2} \int x dx + \frac{1}{a} \int dx \\
     &= \frac{1}{2 a^2} (x^2) + \frac{1}{a} x + C\\
     &= \frac{x^2}{2 a^2} + \frac{x}{a} + C \\\\
0 \leq x < a : F(x) & = \int (- \frac{x}{a^2} + \frac{1}{a} )dx \\
     &= -\frac{1}{a^2} \int x dx + \frac{1}{a} \int dx \\
     &= -\frac{1}{2 a^2} (x^2) + \frac{1}{a} x + C\\
     &= -\frac{x^2}{2 a^2} + \frac{x}{a} + C
\end{align*}


Por lo tanto, la función de distribución queda
\begin{align*}
F(x) =
\left\{
      \begin{array}{ll}
          \frac{x^2}{2 a^2} + \frac{x}{a} + C \quad & -a \leq x < 0 \\
          -\frac{x^2}{2 a^2} + \frac{x}{a} + C & \quad 0 \leq x \leq a\\
          1 & \quad x > a
      \end{array}
\right.
\end{align*}

------------------------------

*Ejercicio 5.* En una comunicación entre un servidor web y un cliente que necesita acceder a un sistema se estudia el
tiempo de llegada de la solicitud y el tiempo transcurrido hasta el ingreso al sistema en el mecanismo
de autenticación. Sean X e Y respectivamente, los períodos de tiempo que se utilizan para cada caso
y suponiendo que la función de densidad conjunta para estas dos variables es:

\begin{align*}
f(x,y) =
\left\{
     \begin{array}{ll}
        2/3(x+2y) \quad & 0 \leq x \leq 1 \cap 0 \leq y \leq 1 \\
        0 & \mbox{otro caso}
     \end{array}
\right.
\end{align*}

a) Hallar la densidad marginal de X.\\
b) Hallar la densidad marginal de Y.\\
c) Encontrar la probabilidad de que la llegada solicitud sea menos de la mitad del tiempo de
ingreso.\\
d) Calcular P(X+Y<1) e interpretar.\\

_Resolución_:\\
*a)* Las funciones de densidad marginales se obtienen integrando en todo en el intervalo para la otra variable
\begin{align*}
f(x) &= 2/3 \int_0^1(x+2y) dy \\
&= 2/3 \cdot (x \cdot [y\big]_0^1 + [y^2\big]_0^1 ) \\
&= \frac{2}{3} ( x + 1 ) = \frac{2}{3} x + \frac{2}{3}
\end{align*}

*b)*
\begin{align*}
f(y) &= 2/3 \int_0^1 (x+2y) dx \\
&= 2/3 ( 1/2 [x^2]_0^1 + 2y [x]_0^1) \\
&= 2/3 (1/2 + 2y) = \frac{1}{3} + \frac{4}{3} y
\end{align*}

*c)*
X: tiempo de la llegada de la solicitud
Y: tiempo de ingreso

\begin{align*}
P(X < \frac{Y}{2}) &= \int_{-\infty}^{+ \infty} \int_{-\infty}^{y/2}  f(x,y) dx dy\\
                   &= \int_{-\infty}^{+ \infty} \int_{-\infty}^{y/2} 2/3 (x+2y) dx dy\\
&= \frac{2}{3} \int_0^1 (\frac{1}{8} y^2 + y^2) dy \\
&= \frac{3}{4} \int_0^1 y^2 dy \\
&= \frac{3}{4} \frac{1}{3} [y^3]_0^1 \\
&= \frac{1}{4} = 0,25 \rightarrow 25\%
\end{align*}

*d)*
\begin{align*}
P(X+Y<1) = P(X<1-Y) &= \frac{2}{3} \int_0^1 \int_0^{1-y} (x+2y) dxdy \\
&= \frac{2}{3} \int_0^1 ( \frac{1}{2} [x^2]_0^{1-y} +2y [x]_0^{1-y} ) dy \\
&= \frac{2}{3} \int_0^1 ( \frac{1}{2}(1-y)^2 + 2y - 2y^2)dy \\
&= \frac{2}{3} ( \frac{1}{2} \int_0^1 (1-y)^2 dy + 2 \int_0^1 y dy - 2 \int_0^1 y^2 dy ) \\
&= \frac{2}{3} ( \frac{1}{6} 
\end{align*}









* Características
** Ejercicio 1
** Ejercicio 4
_Enunciado_:
La función de densidad de probabilidad del tiempo de fallo de un componente electrónico en una copiadora(Y) es la siguiente:

\begin{align*}
f(y)=
\left\{
      \begin{array}{lll}
       \frac{1}{25}y & \mbox{si } 0 \leq y < 5\\
       \frac{2}{5}-\frac{1}{25}y & \mbox{si } 5 \leq y < 10\\
       0 & \mbox{en otro caso}
     \end{array}
\right.
\end{align*}

Calcular E(Y) y V(Y).

Calcular E(1/Y). Qué conclusión obtiene respecto a la relación entre E(1/Y) y 1/E(Y)?\\

\noindent
_Resolución_:


#+begin_export latex
\clearpage
#+end_export


* Modelos probabilísticos
*Ejercicio 1* Algunos economistas han propuesto que haya un control de salarios y precios para combatir la inflación, pero otros consideran que esos controles no son efectivos porque tratan los efectos y no las causas de la inflación. Un reciente estudio revela que el 40% de los adultos están a favor de un control de precios y salarios. Si se seleccionan 5 adultos aleatoriamente, determinar:\\
a) ¿Cuál es la probabilidad de que ninguno esté a favor del citado control.\\
b) ¿Cuál es la probabilidad de que como máximo 3 estén a favor del control?\\
c) ¿Cuál es el valor esperado de adultos seleccionados que están a favor del control?\\

*_Resolución_*:

Sea X el número de adultos que están a favor del control de precios y salarios. X sigue un modelo de ~binomial~ ya que los eventos, estar a favor o estar en contra, son independientes entre sí y a su vez la probabilidad se mantiene invariable luego de realizar la muestra. El primer evento tiene 40% de probabilidad mientras que el segundo tiene 60%.
Los parámetros del modelo son n=5 y p=0,40: 
\begin{align*}
f(x) = \frac{5!} {x!(5-x)!} \cdot 0,40^x \cdot 0,60^{5-x}
\end{align*}

*a)*
\begin{align*}
P(X=0) = f(0) &= \frac{5!} {0!(5-0)!} \cdot 0,40^0 \cdot 0,60^{5-0} \\
&= \frac{5!} {5!} \cdot 0,60^5 \\ = 0,08 \rightarrow 8\%
\end{align*}

*b)*
\begin{align*}
P(X=3) = f(3) &= \frac{5!} {3!(5-3)!} \cdot 0,40^3 \cdot 0,60^{5-3} \\
&= \frac{5!} {3!2!} \cdot 0,40^3 \cdot 0,60^2 \\
&= 10 \cdot 0,064 \cdot 0,36 \\
&= 0,23 \rightarrow 23\%
\end{align*}

*c)*
\begin{align*}
E(X) = n \cdot p = 5 \cdot 0,40 = 2
\end{align*}

------------------------------

*Ejercicio 2)* Se dispone de dos procesadores que funcionan independientemente el uno del otro. Las tareas llegan al procesador i de acuerdo a un proceso de Poisson de parámetro \lambda_i tareas por unidad de tiempo, i = 1, 2. Suponiendo que \lambda_1 = 0.5 y \lambda_2 = 3.5. Determine la probabilidad de que lleguen al menos 2 tareas a cada procesador.\\

*_Resolución_*:
Sea X la cantidad de tareas que llegan al procesador 1 y Y lo mismo para el procesador 2. Ambas variables son discretas y siguen un modelo de Poisson como lo dice el enunciado. La función de cuantía para este modelo para cada procesador es:

\begin{align*}
Procesador\ 1: P(X=x) = f_1(x) &= \frac{ e^{\lambda_1} \lambda^x } {x!}\\
f_1(x) &= \frac{e^{-0,50} 0,50^x} {x!}\\
f_1(x) &= 0,61 \frac{0,50^x} {x!}
\end{align*}

\begin{align*}
Procesador\ 2: P(X=x) = f_2(x) &= \frac{ e^{\lambda_2} \lambda^x } {x!}\\
f_2(x) &= \frac{e^{-3,5} 3,5^x} {x!}\\
f_2(x) &= 0,030 \frac{3,5^x}{x!}
\end{align*}

Entonces, la probabilidad de que llegue al menos 2 tareas al procesador 1 es
\begin{align*}
P(X=2) = f_1(x) &= 0,61 \frac{0,50^2} {2!}\\
&= 0,076 \rightarrow 76\%
\end{align*}

Y para el procesador 2
\begin{align*}
P(X=2) = f_2(x) &= 33,1 \frac{3,5^2} {2!}\\
&= 0,21 \rightarrow 21\%
\end{align*}

Por lo tanto hay más probabilidades de que lleguen al menos 2 tareas al procesador 1 antes que al procesador 2.

------------------------------

*Ejercicio 3)* El servicio de asistencia técnica en una autopista ha comprobado que por las mañanas de los fines de semana el número de llamadas que recibe, por término medio, es de 3 llamadas cada hora. Un operario comienza su jornada de Sábado a las 8 de la mañana. Suponiendo que las llamadas se realizan de forma independiente y con tasa constante:\\
a) ¿Cuál es la probabililad de que reciba 4 llamadas en las dos primeras horas de su jornada de trabajo?\\
b) ¿Cuál es la probabilidad de que reciba la primera llamada antes de las 8:15?\\
c) Si lleva 10 minutos sin recibir ninguna llamada, ¿Cuál es la probabilidad de que reciba una nueva llamada en menos de 15 minutos?\\

*_Resolución_*:
Sea X el número de llamadas que se reciben. X es una variable discreta que sigue el modelo de Poisson dado que entra en juego el tiempo. El parámetro del modelo es $2\cdot\lambda = 3$, dado que se reciben 3 $\frac{llamadas}{hora}$ multiplicado por 2 porque nos interesa considerar 2 horas:

\begin{align*}
P(X=x)= f(x) &= \frac{e^{-\lambda} \lambda^x}{x!}\\
f(x) &= \frac{e^{-6} 6^x} {x!}
\end{align*}

*a)*
\begin{align*}
P(X=4) = f(4) &= \frac{e^{-6} 6^4} {4!} \\
&= 0,13 \rightarrow 13\%
\end{align*}

*b)* Tenemos que adaptar el modelo dado que ahora el parámetro tomará intervalos de a 15 minutos

$$
\lambda_{15 minutos} = \frac{3\ llamadas}{60\ minutos} \cdot  15\ minutos = 0,75
$$

y el f(x) ahora es

$$
f(x) = \frac{e^{-0,75} 0,75^x}{x!}
$$

Tener en cuenta que la definición de X sigue siendo la misma, el número de llamadas.

\begin{align*}
P(X=1) = f(1) = 
#+TITLE: Práctica completa de Estadística
#+DATE: 2022



* TODO Terminar Ejercicio 1.6

* TODO Terminar Ejercicio 2.2.c

* TODO Terminar ejercicio 2.4.b

* TODO Terminar ejercicio 2.5.d

#+begin_export latex
\clearpage
#+end_export

* Probabilidad

*1.* La probabilidad de resolver correctamente un problema con alguna de dos versiones de Octave es 0.45. La de resolver el problema con la primera de estas dos versiones es 0.40 y la de resolverlo con la segunda es 0.30. ¿Es independiente la resolución del problema con estas dos versiones? Justifique.


_Resolución_:
Dado X: la probabilidad de resolver el problema con la 1ra versión y Y: la probabilidad de resolverlo con la 2da versión, las probabilidades del enunciado son:
\begin{align*}
P(X) &= 0,40\\
P(Y) &= 0,30\\
P(X \cup Y ) &= 0,45.
\end{align*}

Para obtener la probabilidad conjunta usamos la fórmula de la probabilidad total.
\begin{align*}
P(X \cup Y ) &= P(X) + P(Y) - P(X \cap Y)\\
P(X \cap Y ) &= P(X) + P(Y) - P(X \cup\\
             &= 0,40 + 0,30 - 0,45\\
	     &= 0,25 \rightarrow 25\%
\end{align*}

Para saber si los eventos X y Y son independientes, su producto debería ser igual a su probabilidad conjunta:
$$
P(X) \cdot P(Y) = 0,40 \cdot 0,30 = 0,12 \neq 0,25 = P(X \cap Y)
$$
y por tanto *no son eventos independientes*.


------------------------------

*2.* Un correo en un Webmail Horde es revisado por dos algoritmos de antispam. Una política de seguridad decide que se muestren aquellos que cuenten con el visto bueno de por lo menos uno de los chequeos. Con este criterio pasan el 80 %. Se sabe que el el 60 % pasó el primer algoritmo y el segundo el 50 %. ¿Cuál hubiese sido el porcentaje de correos mostrados, si se hubiese exigido superar ambas revisiones?

_Resolución_:
Sea A el número de mails que pasan el primer algoritmo  y B los que pasan el segundo. La probabilidad de que un mail pase ambos chequeos simultaneamente $P(A \cap B)$ es
\begin{align*}
P(A) = 0,60 \quad \quad P(B) &= 0,50 \quad \quad P(A \cup B) = 0,80\\\\
P(A \cup B ) &= P(A) + P(B) - P(A \cap B)\\
P(A \cap B ) &= P(A) + P(B) - P(A \cup B)\\
             &= 0,60 + 0,50 - 0,80\\
	     &n= \mathbf{0,30} \rightarrow \mathbf{30\%}
\end{align*}


------------------------------

*3.* En una facultad hay 425 ingresantes de Ingeniería en Informática. En el primer cuatrimestre hay tres asignaturas por cursar: Matemática (A), Química (B) y Física (C). Del SIU Guaraní se obtuvo la siguiente información de cursado:

|-------------------+---------------|
| Asignatura        | N° de alumnos |
|-------------------+---------------|
| A                 |           120 |
| B                 |            70 |
| C                 |            60 |
| $A \cap B$        |            45 |
| $A \cap C$        |            45 |
| $B \cap C$        |            20 |
| $A \cap B \cap C$ |             5 |
|-------------------+---------------|

Suponga que un alumno es elegido al azar. Calcular las probabilidades de que concurra a:
a) Las 3 asignaturas.\\
b) Por lo menos una de las 3.\\
c) Sólo a Física.\\
d) Sólo a una asignatura.\\
e) Matemática pero no a Química.\\
f) Física o Matemática pero no a Química.\\


_Resolución_:

|-------------------+---------------+--------------|
| Asignatura        | N° de alumnos | Probabilidad |
|-------------------+---------------+--------------|
| A                 |           120 | 0,29         |
| B                 |            70 | 0,16         |
| C                 |            60 | 0,14         |
| $A \cap B$        |            45 | 0,11         |
| $A \cap C$        |            10 | 0,02         |
| $B \cap C$        |            20 | 0,05         |
| $A \cap B \cap C$ |             5 | 0,01         |
|-------------------+---------------+--------------|

a) La probabilidad de que concurran a las 3 materias simultáneamente es $P(A \cap B \cap C) = 0,01 \rightarrow 1%$.

b) La probabilidad de que asista a al menos una de las 3 es

\begin{align*}
P(A \cup B \cup C) &= P(A) + P(B) + P(C) - P(A \cap B) - P(A \cap C) - P(B \cap C) - 2P(A \cap B \cap C)\\
&= 0,29 + 0,16 + 0,14 - 0,11 - 0,02 - 0,05 - 2 \cdot 0,01\\
&= 0,39\\
\end{align*}

c)
\begin{align*}
P(C_0) &= P(C) - P(C \cap A) - P(C \cap B)\\
 &= 0,14 - 0,02 - 0,05 = 0,07 \rightarrow 7\%
\end{align*}

------------------------------

*4)*
Dos vendedores de una empresa con distinta antigüedad suelen llegar tarde a su trabajo; la probabili-
dad de que el vendedor con mayor antigüedad llegue tarde cierto día es 0.20; de que el vendedor de
menor antigüedad llegue tarde es 0.15 y de que ambos lleguen tarde es 0.09. Determine la probabili-
dad de que:\\
a) alguno llegue tarde cierto día.\\
b) sólo uno llegue tarde.\\
c) llegue tarde el de menor antigüedad sabiendo que lo hizo el de mayor antigüedad\\

_Resolución_:
Sea A el evento de que el vendedor con mayor antigüedad llegue tarde cierto día y B lo mismo para el vendedor de menor antigüedad, se tiene

$$
P(A) = 0,20 \quad \quad P(B) = 0,15 \quad \quad P(A \cap B) = 0,09
$$

a)
\begin{align*}
P(A \cup B) &= P(A) + P(B) - P(A \cap B)\\
&= 0,20 + 0,15 - 0,09\\
&= 0,26 \rightarrow 26\%
\end{align*}


b) La probabilidad de que sólo A ocurra lo llamamos A_0 y análogamente con B_0.

\begin{align*}
P(A_0) &= P(A) - P(A \cap B)\\
&= 0,20 - 0,09 = 0,11\\\\
P(B_0) &= P(B) - P(A \cap B)\\
&= 0,15 - 0,09 = 0,06
\end{align*}

Por lo tanto la probabilidad de que sólo uno llegue tarde es

$$
P(A_0 \cup B_0) = 0,11 + 0,06 = 0,17 \rightarrow 17\%
$$

\begin{align*}
P(B / A) &= \frac{P(A \cap B)}{P(A)}\\
&= \frac{0,09}{0,20} = 0,45 \rightarrow 45\%
\end{align*}

------------------------------

*5.* Una encuesta a ejecutivos se enfocó a su lealtad a la empresa. Una de las preguntas planteadas fue: Si otra compañía le hiciera una oferta igual o ligeramente mejor que la de su puesto actual, ¿permanecería con la empresa o tomaría el otro empleo? Las respuestas de los 200 ejecutivos de la encuesta se clasificaron en forma cruzada con su tiempo de servicio en la compañía y se muestran en la siguiente tabla.


|         | Tiempo de Servicio(años) | <1 | 1 a 5 | 6 a 10 | >10 |
|---------+--------------------------+----+-------+--------+-----|
| Lealtad | Permanecería             | 10 |    30 |      5 |  75 |
|         | No permanecería          | 25 |    15 |     10 |  30 |

Si se selecciona al azar un ejecutivo, calcule las siguientes probabilidades de los siguientes eventos:\\
a) el ejecutivo seleccionado es leal a la empresa.\\
b) el ejecutivo seleccionado tiene entre 1 y 5 años de servicio.\\
c) el ejecutivo seleccionado no es leal a la empresa y tiene entre 6 y 10 años de servicio.\\
d) Calcule la probabilidad de que el ejecutivo seleccionado tenga más de 10 años de servicio sabiendo que es leal a la empresa.\\


_Resolución_:

a) Sea A el evento de que el ejecutivo sea leal
$$
P(A) = \frac{10+30+5+75}{200} = 0,6 \rightarrow 60\%
$$

b) Sea B el evento de que el ejecutivo tenga entre 1 y 5 años de servicio
$$
P(B) = \frac{30+15}{200} = 0,23 \rightarrow 23\%
$$

c) Sea C el evento de que el ejecutivo no es leal a la empresa y D que tiene entre 6 a 10 años
$$P(C \cap D) = \frac{10}{200} = 0,05 \rightarrow 5\%$$

d) Sea E el evento de que el ejecutivo tenga más de 10 años en la empresa

$$P(E / A) = \frac{P(E \cap A)}{P(A)} = \frac{75/200}{0,6} = 0,62 \rightarrow 63\%$$

------------------------------

*6.* De los aspirantes a ingresar la tecnicatura en Software Libre el 40 % son varones, de los cuales sólo el 20 % ya es alumno de la UNL, mientras que entre las mujeres, el 30 % ya son alumnas. Se elige un aspirante al azar.
a) ¿Cuál es la probabilidad de que ya sea alumno?\\
b) Si el estudiante elegido ya es alumno, ¿cuál es la probabilidad de que sea varón?\\
c) ¿Cuál es la probabilidad de que sea mujer o que no sea alumno?\\

_Resolución_:

a) La probabilidad de que ya sea alumno puede obtenerse realizando un árbol de probabilidades resultando la probabilidad:
\begin{align*}
P(A) = P(A \cap V ) + P(A \cap M) &= P(V) \cdot P(A / V) + P(M) \cdot P(A / M)\\
&= 0,40 \cdot 0,20 + 0,60 \cdot 0,30 = 0,26 \rightarrow 26\%
\end{align*}

b)
\begin{align*} 
P( V / A ) &= \frac{P(V \cap A)}{P(A)}\\
&= \frac{P(V) \cdot P(A/V)} {P(A)} \\
&= \frac{0,40 \cdot 0,20} {0,26} \\
&= 0,31 \rightarrow 31\%
\end{align*}


c)

\begin{align*}
P(M \cup \bar{A}) &= P(M) + P(\bar{A}) \\
&= P(M) + P(V \cap \bar{A} ) + P(M \cap \bar{A} ) \\
&= 0,60 + 0,32 + 0,42 \\
&= 0,86 \rightarrow 86\%
\end{align*}


------------------------------

*7.* Los habitantes en situación de empleo de una determinada ciudad se ha dividido en función de sus ingresos anuales en tres grupos: el 20% tiene ingresos bajos, el 70% ingresos medios y el resto ingresos altos. Se ha determinado que la proporción de la población con estos ingresos que posee título universitario es 0.1, 0.9 y 0.3 respectivamente.\\
a) Determine, al elegir al azar un habitante, la probabilidad de que posea título universitario.\\
b) Si la persona seleccionada tiene título universitario, ¿a qué grupo pertenecería más probablemente?\\

_Resolución_:

Sean B ingresos bajos, M ingresos medios, A ingresos altos, T estudios universitarios. 

a)
\begin{align*}
P(T) &= P(T \cap B) + P(T \cap M) + P(T \cap A)\\
&= P(B) \cdot P(T / B) + P(M) \cdot P(T / M) + P(A) \cdot P(T / A)\\
&= 0,20 \cdot 0,1 + 0,70 \cdot 0,90 + 0,10 \cdot 0,30\\
&= 0,68 \rightarrow 68\%
\end{align*}

b)
\begin{align*}
P(B/T) &= \frac{P(B \cap T)}{P(T)} = \frac{0,03}{0,68} = 0,04 \rightarrow 4\% \\
P(M/T) &= \frac{P(M \cap T)}{P(T)} = \frac{0,63}{0,68} = 0,93 \rightarrow 93\% \\
P(A/T) &= \frac{P(A \cap T)}{P(T)} = \frac{0,02}{0,68} = 0,03 \rightarrow 3\%
\end{align*}

Por lo tanto, es más probable que pertenezca al grupo de ingresos medios.

------------------------------

*8.* En una fábrica de discos de estado sólido, el 20 % de los mismos se montan en la primera planta, el 30 % en la segunda y el 50 % restante en la tercera. Se sabe además que la cadena de montaje falla, dando lugar a una disco defectuoso, con probabilidades 0.1, 0.2 y 0.15 en cada una de las tres plantas respectivamente. Se selecciona al azar un disco montado en esa fábrica.\\
a) Determine la probabilidad de que sea defectuoso.\\
b) ¿Cuál es la probabilidad de que se haya montado en la primera planta sabiendo que es defectuoso?\\
c) Si el disco seleccionada resultó no defectuoso, ¿cuál es la probabilidad de que haya sido montado en la tercera planta.\\


_Resolución_:
Sea A el evento de que los discos se monten en la primera planta, B en la segunda y C en la tercera; y F el suceso de que el disco esté defectuoso. El enunciado nos da las siguientes probabilidades

\begin{align*}
&P(A) = 0,20      && P(B) = 0,30      &&& P(C) = 0,50\\
&P(F / A) = 0,10  && P(F / B) = 0,20  &&& P(F / C) = 0,15
\end{align*}

a)
\begin{align*}
P(F) &= P(F \cap A) + P(F \cap B) + P(F \cap C)\\
     &= P(A) \cdot P(F/A) + P(B) \cdot P(F/B) + P(C) \cdot P(F/C)\\
     &= 0,20 \cdot 0,10 + 0,30 \cdot 0,20 + 0,50 \cdot 0,15\\
     &= 0,16 \rightarrow 16\%
\end{align*}

b)
\begin{align*}
P(A/F) &= \frac{ P(A \cap F)} {P(F)} = \frac{0,02}{0,16}\\
       &= 0,13 \rightarrow 13\% 
\end{align*}

c)
$$
P(\bar{F})=1-P(F) = 1 - 0,16 = 0,84 \rightarrow 84\%
$$

\begin{align*}
P(C / \bar{F}) &= \frac{ P(C \cap \bar{F})} {P(\bar{F})}\\
               &= \frac{ P(C) \cdot P(\bar{F}/C)} {P(\bar{F})}\\
               &= \frac{0,50 \cdot 0,85} {0,84}\\
               &= 0,51 \rightarrow 51\%
\end{align*}


#+begin_export latex
\clearpage
#+end_export


* Variables aleatorias
*Ejercicio 1)* La distribución de probabilidad de X: "número de errores en un canal de transmisión" se presenta en la siguiente tabla:

|------+------+------+------+------+------|
| X    |    0 |    1 |    2 |    3 |    4 |
|------+------+------+------+------+------|
| f(x) | 0.41 | 0.37 | 0.16 | 0.05 | 0.01 |
|------+------+------+------+------+------|

Determinar la función acumulativa de X y utilizar la para determinar la probabilidad de encontrar más de 3 errores en el canal.

_Resolución_
|------+---+------+------+------+------+----|
| X    | 0 |    1 |    2 |    3 |    4 | >4 |
|------+---+------+------+------+------+----|
| F(x) | 0 | 0.41 | 0.78 | 0.94 | 0.99 |  1 |
|------+---+------+------+------+------+----|

La probabilidad de encontrar más de 3 errores es

$$
P(X>3) = 1 - P(X \leq 3) = 1 - 0.99 = 0.01 \Rightarrow 1\%.
$$

------------------------------

*Ejercicio 2.* Se está realizando un estudio en un sistema y se analiza una variable aleatoria X con función dada por:
\begin{align*}
F(x) = 
\left\{
      \begin{array}{ll}
            1-e^{-x} & \mbox{si } x > 0 \\
	    0        & \mbox{si } x \leq 0
      \end{array}
\right.
\end{align*}

a) Obtener P(X>2).\\

b) Considerar una nueva variable aleatoria Y que también es necesaria para el estudio de manera que la función de densidad conjunta de las variables es:

\begin{align*}
f(x,y) =
\left\{
      \begin{array}{ll}
            ye^{-(x+y)} & \mbox{si } x > 0 \land y > 0 \\
            0           & \mbox{en otro caso}
       \end{array}
\right.
\end{align*}

Indicar de forma razonada si se puede considerar que ambas variables son independientes ya que de esta conclusión depende parte del estudio.\\

c) En cualquier caso, calcular P(Y < 1 | X > 2).\\

_Resolución_:\\
*a)* La forma más rápida de hallar P(X>2) es mediante la función acumulativa que nos da el problema F(x), la cual por definición es la probabilidad de que la variable X sea menor o igual a cierto valor. Entonces
\begin{align*}
P(X > 2 ) & = 1 - P(X \leq 2 ) \quad \quad \mbox{Uso del complemento}\\
          & = 1 - F(2)\\
          & = 1 - (1 - e^{-2})\\
          & = 1 - 0,86 = 0,14 \Rightarrow \mathbf{14\%}
\end{align*}


La otra forma para hallar P(X>2) es hallando f(x) e integrando en el intervalo que nos interese saber su probabilidad. Para hallar f(x) mediante F(x), derivamos F(x) respecto de x.

\begin{align*}
\frac{d}{dx} F(x) &= \frac{d}{dx}(1-e^{-x})\\
                  &= \frac{d}{dx} 1 - \frac{d}{dx} e^{-x}\\
             \mathbf{f(x)} &= \mathbf{e^{-x}}
\end{align*}

Y ahora integramos respecto a x en el intervalo [2,+\infty)

\begin{align*}
P(X>2) = \int_2^{+ \infty} f(x)dx &= \int_2^{+ \infty} e^{-x} dx\\
       &= -e^{-x} \Big]_2^{+ \infty}\\
       &= e^{-2} - e^{-\infty} = 0,13 \Rightarrow \mathbf{13\%}
\end{align*}

*b)* Para saber si ambas variables son independientes se debe comprobar
$$
f(x,y) = f(x)\cdot f(y)
$$
por lo que vamos a obtener las funciones marginales para cada variable y comprobar si esta igualdad se cumple.

\begin{align*}
f(x) &= \int_{-\infty}^{ +\infty} f(x,y) dy \\
     &= \int_{0}^{ +\infty} y \cdot e^{-(x+y)} dy \\
     &= \int_{0}^{ +\infty} y \cdot e^{-x} \cdot e^{-y} dy \\
     &= e^{-x} \cdot \int_{0}^{ +\infty} y \cdot e^{-y} dy \\
     &= e^{-x} \cdot (-e^{-y} \cdot y - e^{-y})_0^{ + \infty} \\
f(x) &= e^{-x}\\\\
f(y) &= \int_{-\infty}^{+ \infty} f(x,y) dx\\
     &= \int_0^{ +\infty} y \cdot e^{-(x+y)} dx \\
     &= y \cdot e^{-y} \int_0^{ +\infty} e^{-x} dx \\
f(y) &= y \cdot e^{-y}
\end{align*}

Al realizar el producto

$$
f(x) \cdot f(y) = e^{-x} \cdot y \cdot e^{-y} = y \cdot e^{-(x+y)} = f(x,y)
$$
y por tanto son independientes.

*c)*

\begin{align*}
P(Y < 1 / X > 2) &= \frac{ P(Y < 1 \cap X > 2)} { P(X>2)} \\
\end{align*}


------------------------------

*Ejercicio 3.* Se conoce que la duración (en días) de un disco rígido es una variable aleatoria que se distribuye según la siguiente función:

\begin{align*}
f(x) =
\left\{
       \begin{array}{ll}
              1000/x^2 & \mbox{si } x > 1000 \\
              0 & \mbox{en otro caso}
       \end{array}
\right.
\end{align*}

Cuál es la probabilidad de que en un disco rígido dure menos de 2000 días, si se conoce que el disco funciona aún después de 1500 días de uso de la máquina?\\\\


_Resolución_: Esto es una probabilidad condicional que se calcula de la siguiente forma
\begin{align*}
    P(X < 2000 / X > 1500) &= \frac{ P( X < 2000 \cap X > 1500)} {P(X >1500)} \\
                           &= \frac{ \int_{1500}^{2000} 1000/x^2 dx } { \int_{1500}^{\infty} 1000/x^2 dx} \\
                           &= \frac{ -1000 [1/x]_{1500}^{2000} } { -1000 [1/x]_{1500}^{\infty} } \\
                           &= \frac{ 1/2000 - 1/1500 } { 1/\infty - 1/1500 } \\
                           &= 0,25 \rightarrow 25\%
\end{align*}


------------------------------

*Ejercicio 4.* Una variable aleatoria está distribuida según la ley que se muestra en la figura:



a) Encontrar una expresión para la función de densidad y verificar que sea válida.

b) Obtener la función de distribución correspondiente.\\

_Resolución_:
a)
\begin{align*}
f(x) =
\left\{
      \begin{array}{ll}
          \frac{x}{a^2} + \frac{1}{a} & \quad -a \leq x < 0 \\
          \frac{-x}{a^2} + \frac{1}{a} & \quad 0 \leq x \leq a\\
          0 & \mbox{En otro caso}
      \end{array}
\right.
\end{align*}

La probabilidad es el área bajo la función que puede calcularsse como dos mitades de un triangulo de lados $a$ y $1/a$

$$
Area = 2 \cdot \frac{a \cdot 1/a}{2} = \frac{2}{2}= 1
$$
por lo tanto es una función de probabilidad.\\

b) La función de distribución se obtiene integrando indefinidamente respecto a x ambas partes de la función
\begin{align*}
-a \leq x < 0 : F(x) & = \int \frac{x}{a^2} + \frac{1}{a} dx \\
     &= \frac{1}{a^2} \int x dx + \frac{1}{a} \int dx \\
     &= \frac{1}{2 a^2} (x^2) + \frac{1}{a} x + C\\
     &= \frac{x^2}{2 a^2} + \frac{x}{a} + C \\\\
0 \leq x < a : F(x) & = \int (- \frac{x}{a^2} + \frac{1}{a} )dx \\
     &= -\frac{1}{a^2} \int x dx + \frac{1}{a} \int dx \\
     &= -\frac{1}{2 a^2} (x^2) + \frac{1}{a} x + C\\
     &= -\frac{x^2}{2 a^2} + \frac{x}{a} + C
\end{align*}


Por lo tanto, la función de distribución queda
\begin{align*}
F(x) =
\left\{
      \begin{array}{ll}
          \frac{x^2}{2 a^2} + \frac{x}{a} + C \quad & -a \leq x < 0 \\
          -\frac{x^2}{2 a^2} + \frac{x}{a} + C & \quad 0 \leq x \leq a\\
          1 & \quad x > a
      \end{array}
\right.
\end{align*}

------------------------------

*Ejercicio 5.* En una comunicación entre un servidor web y un cliente que necesita acceder a un sistema se estudia el
tiempo de llegada de la solicitud y el tiempo transcurrido hasta el ingreso al sistema en el mecanismo
de autenticación. Sean X e Y respectivamente, los períodos de tiempo que se utilizan para cada caso
y suponiendo que la función de densidad conjunta para estas dos variables es:

\begin{align*}
f(x,y) =
\left\{
     \begin{array}{ll}
        2/3(x+2y) \quad & 0 \leq x \leq 1 \cap 0 \leq y \leq 1 \\
        0 & \mbox{otro caso}
     \end{array}
\right.
\end{align*}

a) Hallar la densidad marginal de X.\\
b) Hallar la densidad marginal de Y.\\
c) Encontrar la probabilidad de que la llegada solicitud sea menos de la mitad del tiempo de
ingreso.\\
d) Calcular P(X+Y<1) e interpretar.\\

_Resolución_:\\
*a)* Las funciones de densidad marginales se obtienen integrando en todo en el intervalo para la otra variable
\begin{align*}
f(x) &= 2/3 \int_0^1(x+2y) dy \\
&= 2/3 \cdot (x \cdot [y\big]_0^1 + [y^2\big]_0^1 ) \\
&= \frac{2}{3} ( x + 1 ) = \frac{2}{3} x + \frac{2}{3}
\end{align*}

*b)*
\begin{align*}
f(y) &= 2/3 \int_0^1 (x+2y) dx \\
&= 2/3 ( 1/2 [x^2]_0^1 + 2y [x]_0^1) \\
&= 2/3 (1/2 + 2y) = \frac{1}{3} + \frac{4}{3} y
\end{align*}

*c)*
X: tiempo de la llegada de la solicitud
Y: tiempo de ingreso

\begin{align*}
P(X < \frac{Y}{2}) &= \int_{-\infty}^{+ \infty} \int_{-\infty}^{y/2}  f(x,y) dx dy\\
                   &= \int_{-\infty}^{+ \infty} \int_{-\infty}^{y/2} 2/3 (x+2y) dx dy\\
&= \frac{2}{3} \int_0^1 (\frac{1}{8} y^2 + y^2) dy \\
&= \frac{3}{4} \int_0^1 y^2 dy \\
&= \frac{3}{4} \frac{1}{3} [y^3]_0^1 \\
&= \frac{1}{4} = 0,25 \rightarrow 25\%
\end{align*}

*d)*
\begin{align*}
P(X+Y<1) = P(X<1-Y) &= \frac{2}{3} \int_0^1 \int_0^{1-y} (x+2y) dxdy \\
&= \frac{2}{3} \int_0^1 ( \frac{1}{2} [x^2]_0^{1-y} +2y [x]_0^{1-y} ) dy \\
&= \frac{2}{3} \int_0^1 ( \frac{1}{2}(1-y)^2 + 2y - 2y^2)dy \\
&= \frac{2}{3} ( \frac{1}{2} \int_0^1 (1-y)^2 dy + 2 \int_0^1 y dy - 2 \int_0^1 y^2 dy ) \\
&= \frac{2}{3} ( \frac{1}{6} 
\end{align*}









* Características
** Ejercicio 1
** Ejercicio 4
_Enunciado_:
La función de densidad de probabilidad del tiempo de fallo de un componente electrónico en una copiadora(Y) es la siguiente:

\begin{align*}
f(y)=
\left\{
      \begin{array}{lll}
       \frac{1}{25}y & \mbox{si } 0 \leq y < 5\\
       \frac{2}{5}-\frac{1}{25}y & \mbox{si } 5 \leq y < 10\\
       0 & \mbox{en otro caso}
     \end{array}
\right.
\end{align*}

Calcular E(Y) y V(Y).

Calcular E(1/Y). Qué conclusión obtiene respecto a la relación entre E(1/Y) y 1/E(Y)?\\

\noindent
_Resolución_:


#+begin_export latex
\clearpage
#+end_export


* Modelos probabilísticos
*Ejercicio 1* Algunos economistas han propuesto que haya un control de salarios y precios para combatir la inflación, pero otros consideran que esos controles no son efectivos porque tratan los efectos y no las causas de la inflación. Un reciente estudio revela que el 40% de los adultos están a favor de un control de precios y salarios. Si se seleccionan 5 adultos aleatoriamente, determinar:\\
a) ¿Cuál es la probabilidad de que ninguno esté a favor del citado control.\\
b) ¿Cuál es la probabilidad de que como máximo 3 estén a favor del control?\\
c) ¿Cuál es el valor esperado de adultos seleccionados que están a favor del control?\\

*_Resolución_*:

Sea X el número de adultos que están a favor del control de precios y salarios. X sigue un modelo de ~binomial~ ya que los eventos, estar a favor o estar en contra, son independientes entre sí y a su vez la probabilidad se mantiene invariable luego de realizar la muestra. El primer evento tiene 40% de probabilidad mientras que el segundo tiene 60%.
Los parámetros del modelo son n=5 y p=0,40: 
\begin{align*}
f(x) = \frac{5!} {x!(5-x)!} \cdot 0,40^x \cdot 0,60^{5-x}
\end{align*}

*a)*
\begin{align*}
P(X=0) = f(0) &= \frac{5!} {0!(5-0)!} \cdot 0,40^0 \cdot 0,60^{5-0} \\
&= \frac{5!} {5!} \cdot 0,60^5 \\ = 0,08 \rightarrow 8\%
\end{align*}

*b)*
\begin{align*}
P(X=3) = f(3) &= \frac{5!} {3!(5-3)!} \cdot 0,40^3 \cdot 0,60^{5-3} \\
&= \frac{5!} {3!2!} \cdot 0,40^3 \cdot 0,60^2 \\
&= 10 \cdot 0,064 \cdot 0,36 \\
&= 0,23 \rightarrow 23\%
\end{align*}

*c)*
\begin{align*}
E(X) = n \cdot p = 5 \cdot 0,40 = 2
\end{align*}

------------------------------

*Ejercicio 2)* Se dispone de dos procesadores que funcionan independientemente el uno del otro. Las tareas llegan al procesador i de acuerdo a un proceso de Poisson de parámetro \lambda_i tareas por unidad de tiempo, i = 1, 2. Suponiendo que \lambda_1 = 0.5 y \lambda_2 = 3.5. Determine la probabilidad de que lleguen al menos 2 tareas a cada procesador.\\

*_Resolución_*:
Sea X la cantidad de tareas que llegan al procesador 1 y Y lo mismo para el procesador 2. Ambas variables son discretas y siguen un modelo de Poisson como lo dice el enunciado. La función de cuantía para este modelo para cada procesador es:

\begin{align*}
Procesador\ 1: P(X=x) = f_1(x) &= \frac{ e^{\lambda_1} \lambda^x } {x!}\\
f_1(x) &= \frac{e^{-0,50} 0,50^x} {x!}\\
f_1(x) &= 0,61 \frac{0,50^x} {x!}
\end{align*}

\begin{align*}
Procesador\ 2: P(X=x) = f_2(x) &= \frac{ e^{\lambda_2} \lambda^x } {x!}\\
f_2(x) &= \frac{e^{-3,5} 3,5^x} {x!}\\
f_2(x) &= 0,030 \frac{3,5^x}{x!}
\end{align*}

Entonces, la probabilidad de que llegue al menos 2 tareas al procesador 1 es
\begin{align*}
P(X=2) = f_1(x) &= 0,61 \frac{0,50^2} {2!}\\
&= 0,076 \rightarrow 76\%
\end{align*}

Y para el procesador 2
\begin{align*}
P(X=2) = f_2(x) &= 33,1 \frac{3,5^2} {2!}\\
&= 0,21 \rightarrow 21\%
\end{align*}

Por lo tanto hay más probabilidades de que lleguen al menos 2 tareas al procesador 1 antes que al procesador 2.

------------------------------

*Ejercicio 3)* El servicio de asistencia técnica en una autopista ha comprobado que por las mañanas de los fines de semana el número de llamadas que recibe, por término medio, es de 3 llamadas cada hora. Un operario comienza su jornada de Sábado a las 8 de la mañana. Suponiendo que las llamadas se realizan de forma independiente y con tasa constante:\\
a) ¿Cuál es la probabililad de que reciba 4 llamadas en las dos primeras horas de su jornada de trabajo?\\
b) ¿Cuál es la probabilidad de que reciba la primera llamada antes de las 8:15?\\
c) Si lleva 10 minutos sin recibir ninguna llamada, ¿Cuál es la probabilidad de que reciba una nueva llamada en menos de 15 minutos?\\

*_Resolución_*:
Sea X el número de llamadas que se reciben. X es una variable discreta que sigue el modelo de Poisson dado que entra en juego el tiempo. El parámetro del modelo es $2\cdot\lambda = 3$, dado que se reciben 3 $\frac{llamadas}{hora}$ multiplicado por 2 porque nos interesa considerar 2 horas:

\begin{align*}
P(X=x)= f(x) &= \frac{e^{-\lambda} \lambda^x}{x!}\\
f(x) &= \frac{e^{-6} 6^x} {x!}
\end{align*}

*a)*
\begin{align*}
P(X=4) = f(4) &= \frac{e^{-6} 6^4} {4!} \\
&= 0,13 \rightarrow 13\%
\end{align*}

*b)* Tenemos que adaptar el modelo dado que ahora el parámetro tomará intervalos de a 15 minutos

$$
\lambda_{15 minutos} = \frac{3\ llamadas}{60\ minutos} \cdot  15\ minutos = 0,75
$$

y el f(x) ahora es

$$
f(x) = \frac{e^{-0,75} 0,75^x}{x!}
$$

Tener en cuenta que la definición de X sigue siendo la misma, el número de llamadas.

\begin{align*}
P(X=1) = f(1) &= \frac{e^{-0,75} 0,75^1}{1!} \\
&= 0,35 \rightarrow 35\%
\end{align*}

*c)* Esta probabilidad es una condicional de la siguiente forma

$$P(X=1 / X=0)$$ 

El numerador corresponde a un \lambda_{15\ minutos} similar al del inciso b, y el denominador a un \lambda_{10\ minutos} que debemos de calcular.

$$
\lambda_{10\ minutos} = \frac{3\ llamadas}{60\ minutos} \cdot  10\ minutos = 0,5
$$

y su función Poisson queda
$$
f(x)_{10\ minutos} = \frac{e^{-0,5} 0,5^x} {x!}
$$

Finalmente resolvemos la probabilidad condicional


\begin{align*}
P(X=1 / X=0) = \frac{ P(X = 1 \cap X = 0 ) } {P(X=0)} \\
&= 
\end{align*}
